#!/usr/bin/python2.7

# Project Euler - Problem 2 Solution
# https://projecteuler.net/problem=2
# Sam Olds

# Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def main():
  old2 = 1
  old1 = 2
  runningSum = 0
  while old1 < 4000000:

    if old1 % 2 == 0:
      runningSum += old1

    temp = old1
    old1 = old1 + old2
    old2 = temp
  print runningSum


if __name__ == '__main__':
  main()
